### Fetch all TODOs
GET {{base-url}}/api/v1/todos
Accept: application/json

### Fetch a specific TODO
GET {{base-url}}/api/v1/todos/1
Accept: application/json

### Create a category
POST {{base-url}}/api/v1/todos
Content-Type: application/json
Accept: application/json

{
    "title": "Work all day",
    "description": "Work all day and all night",
    "completed": false
}


### Update a TODO
PUT {{base-url}}/api/v1/todos/1
Content-Type: application/json
Accept: application/json

{
  "title": "Work all day!",
  "description": "Work all day and all night",
  "completed": false
}


### Delete a category
DELETE {{base-url}}/api/v1/todos/1


### Delete all categories
DELETE {{base-url}}/api/v1/todos/
