apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-pod-liveness-probe
  name: demo-pod-liveness-probe
spec:
  containers:
  - name: demo-container-ssl
    image: andreifecioru/k8s_demo_app:x86_0.2
    stdin: true
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: http
    

  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    livenessProbe:
      httpGet:
        path: /ready
        port: admin
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 3


