version: '2.1'

services:
  java:
    extends:
      file: java/compose.yml
      service: java

  zk:
    extends:
      file: zookeeper/compose.yml
      service: zk

  zk-api:
    extends:
      file: zookeeper/compose.yml
      service: zk-api
    depends_on:
      - zk
    links:
      - zk:zk

  zk-web:
    extends:
      file: zookeeper/compose.yml
      service: zk-web
    depends_on:
      - zk-api

  hadoop:
    extends:
      file: hadoop/compose.yml
      service: hadoop

  hbase:
    extends:
      file: hbase/compose.yml
      service: hbase
    depends_on:
      - zk
      - hadoop
    links:
      - zk:zk
      - hadoop:hadoop

  kafka:
    extends:
      file: kafka/compose.yml
      service: kafka
    depends_on:
      - zk
    links:
      - zk:zk

  kafka_manager:
    extends:
      file: kafka/compose.yml
      service: kafka_manager
    depends_on:
      - zk
      - kafka
    links:
      - zk:zk
