apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-pod-ssl
  name: demo-pod-ssl
spec:
  containers:
  - name: demo-container-ssl
    image: andreifecioru/k8s_demo_app:darwin_0.2
    stdin: true
    ports:
    - name: http
      containerPort: 8080

  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901


