users: list[dict[str, str]] = [
    {"first_name": "John", "last_name": "Doe", "username": "johndoe", "email": "john.doe@email.com"},
    {"first_name": "Jane", "last_name": "Smith", "username": "janesmith", "email": "jane.smith@email.com"},
    {"first_name": "Alice", "last_name": "Brown", "username": "alicebrown", "email": "alice.brown@email.com"},
    {"first_name": "Bob", "last_name": "Martin", "username": "bobmartin", "email": "bob.martin@email.com"},
    {"first_name": "Carol", "last_name": "White", "username": "carolwhite", "email": "carol.white@email.com"},
    {"first_name": "David", "last_name": "Lee", "username": "davidlee", "email": "david.lee@email.com"},
    {"first_name": "Eva", "last_name": "Green", "username": "evagreen", "email": "eva.green@email.com"},
    {"first_name": "Frank", "last_name": "Castle", "username": "frankcastle", "email": "frank.castle@email.com"},
    {"first_name": "Grace", "last_name": "Hall", "username": "gracehall", "email": "grace.hall@email.com"},
    {"first_name": "Henry", "last_name": "Ford", "username": "henryford", "email": "henry.ford@email.com"},
]

posts: list[dict[str,
                 str]] = [{"author": "johndoe",
                           "title": "This is about FastAPI",
                           "content": "This is something that I need to learn fast.",
                           },
                          {"author": "janesmith",
                           "title": "Getting Started with Pydantic",
                           "content": "Pydantic makes data validation straightforward by leveraging Python type hints.",
                           },
                          {"author": "alicebrown",
                           "title": "Understanding Path Parameters",
                           "content": "Path parameters let you capture dynamic values directly from the URL.",
                           },
                          {"author": "bobmartin",
                           "title": "Query Parameters Explained",
                           "content": "Query parameters are optional by default and great for filtering or pagination.",
                           },
                          {"author": "carolwhite",
                           "title": "Request Body and Pydantic Models",
                           "content": "Defining a Pydantic model for your request body gives you free validation and docs.",
                           },
                          {"author": "davidlee",
                           "title": "Response Models in FastAPI",
                           "content": "Response models let you control exactly what data gets serialized back to the client.",
                           },
                          {"author": "evagreen",
                           "title": "Dependency Injection Basics",
                           "content": "FastAPI's dependency system is one of its most powerful features for sharing logic.",
                           },
                          {"author": "frankcastle",
                           "title": "Connecting to a Database",
                           "content": "SQLAlchemy integrates cleanly with FastAPI through dependency injection and sessions.",
                           },
                          {"author": "gracehall",
                           "title": "JWT Authentication Flow",
                           "content": "Stateless auth with JWT means the server never needs to store session data.",
                           },
                          {"author": "henryford",
                           "title": "Deploying FastAPI with Docker",
                           "content": "Containerising your app makes deployments reproducible across any environment.",
                           },
                          ]
